Blog/urls.py
from django.urls import path

from . import views

app_name = "Blog"

urlpatterns = [

    path(
        "posts/<int:post_id>/",
        views.PostDetailView.as_view(),
        name="post_detail"),

    path(
        'posts/<int:post_id>/edit/',
        views.PostUpdateView.as_view(),
        name='edit_post'),

    path(
        'posts/<int:post_id>/delete/',
        views.PostDeleteView.as_view(),
        name='delete_post'),

    path('posts/create/',
         views.PostCreateView.as_view(),
         name="create_post"),

    path(
        'category/<slug:category_slug>/',
        views.CategoryListView.as_view(),
        name='category_posts',
    ),

    path(
        'categories/',
        views.CategoryAllListView.as_view(),
        name='category_list'),

    path(
        'posts/<int:post_id>/comment/',
        views.CommentCreateView.as_view(),
        name='add_comment',
    ),
    path(
        'posts/<int:post_id>/edit_comment/<int:comment_id>/',
        views.CommentUpdateView.as_view(),
        name='edit_comment',
    ),
    path(
        'posts/<int:post_id>/delete_comment/<int:comment_id>/',
        views.CommentDeleteView.as_view(),
        name='delete_comment',
    ),
]

CreatingSuccess/urls.py
from django.contrib import admin
from django.urls import path, include, reverse_lazy

from django.views.generic.edit import CreateView
from django.conf.urls.static import static
from django.conf import settings
from django.urls import re_path
from django.views.static import serve

from django.contrib.auth.views import (
    LoginView,
    LogoutView,
    PasswordChangeView,
    PasswordResetView,
    PasswordResetConfirmView,
)
from CustomUser.forms import CustomUserCreationForm


handler404 = "Pages.views.page_not_found"
handler500 = "Pages.views.internal_server_error"

urlpatterns = [
    path("admin/", admin.site.urls),

    path("", include("Blog.urls")),

    path("", include("Pages.urls")),

    path("", include("CustomUser.urls")),

    path(
        'registration/',
        CreateView.as_view(
            template_name='registration/registration_form.html',
            form_class=CustomUserCreationForm,

            success_url=reverse_lazy('Pages:index'),
        ),
        name='registration',
    ),

    path(
        'login/',
        LoginView.as_view(template_name='registration/login.html'),
        name='login'
    ),
    path(
        'logout/',
        LogoutView.as_view(),
        name='logout'
    ),
    path(
        'password_change/',
        PasswordChangeView.as_view(template_name='password_change.html'),
        name='password_change'
    ),
    path(
        'password_reset/',
        PasswordResetView.as_view(template_name='password_reset.html'),
        name='password_reset'
    ),
    path(
        'password_reset_confirm/<uidb64>/<token>/',
        PasswordResetConfirmView.as_view(template_name='password_reset_confirm.html'),
        name='password_reset_confirm'
    ),


] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

if not settings.DEBUG:
    urlpatterns += [re_path(r'^media/(?P<path>.*)$',
                            serve,
                            {'document_root': settings.MEDIA_ROOT}),
                    re_path(r'^static/(?P<path>.*)$',
                            serve,
                            {'document_root': settings.STATIC_ROOT}),]

CustomUser/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static

from .views import UserProfileEditView, UserProfileView

app_name = 'Profile'

urlpatterns = [
    path(
        'view/<str:username>/',
        UserProfileView.as_view(),
        name='view_profile'
    ),
    path(
        'edit/<str:username>/',
        UserProfileEditView.as_view(),
        name='edit_profile'
    ),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/includes/category_link.html
<a class="text-muted" href="{% url 'Blog:category_posts' post.category.slug %}">
  {{ post.category.title }}
</a>

templates/includes/comments.html
{% if user.is_authenticated %}
  {% load django_bootstrap5 %}
  <h5 class="mb-4">Оставить комментарий</h5>
  <form method="post" action="{% url 'Blog:add_comment' post.id %}">
    {% csrf_token %}
    {% bootstrap_form form %}
    {% bootstrap_button button_type="submit" content="Отправить" %}
  </form>
{% endif %}
<br>
{% for comment in comments %}
  <div class="media mb-4">
    <div class="media-body">
      <h5 class="mt-0">
        <a href="{% url 'Profile:view_profile' comment.author.username %}" name="comment_{{ comment.id }}">
          @{{ comment.author.username }}
        </a>
      </h5>
      <small class="text-muted">{{ comment.created_at }}</small>
      <br>
      {{ comment.text|linebreaksbr }}
    </div>
    {% if user == comment.author %}
      <a class="btn btn-sm text-muted" href="{% url 'Blog:edit_comment' post.id comment.id %}" role="button">
        Отредактировать комментарий
      </a>
      <a class="btn btn-sm text-muted" href="{% url 'Blog:delete_comment' post.id comment.id %}" role="button">
        Удалить комментарий
      </a>
    {% endif %}
  </div>
{% endfor %}

templates/includes/footer.html
<footer class="border-top text-center py-3">
  <p>© Creating Success</p>    
</footer>

templates/includes/header.html
{% load static %}
<style>
  .custom-link {
    color: #000000 !important; /* Чёрный цвет для ссылок */
    text-decoration: none; /* Убираем подчеркивание */
    padding: 10px; /* Добавляем отступы для удобства */
    transition: background-color 0.3s, color 0.3s; /* Плавный переход */
  }

  .custom-link:hover {
    color: #ffffff; /* Белый цвет текста при наведении */
    background-color: #333333 !important; /* Темный фон при наведении */
  }

  .custom-link.active, .custom-link:focus {
    color: #ffffff; /* Белый цвет текста при активном состоянии */
    background-color: #A57BCA !important; /* Светло-фиолетовый фон при активном состоянии */
  }

  .custom-link:visited {
    color: #000000 !important; /* Чёрный цвет для посещённых ссылок */
  }

  .btn-custom {
    color: #000000; /* Чёрный цвет для кнопок */
    background-color: transparent; /* Прозрачный фон для кнопок по умолчанию */
    border-color: #000000; /* Чёрная рамка */
    margin-right: 10px; /* Отступ справа между кнопками */
    margin-bottom: 5px; /* Отступ снизу между кнопками */
    transition: background-color 0.3s, color 0.3s; /* Плавный переход */
    width: 100px; /* Задайте одинаковую ширину для всех кнопок */
    height: 45px; /* Задайте одинаковую высоту для всех кнопок */
    display: flex; /* Используем flex для центрирования текста */
    align-items: center; /* Выравнивание по вертикали */
    justify-content: center; /* Выравнивание по горизонтали */
  }

  .btn-custom:hover {
    color: #ffffff; /* Белый цвет текста при наведении */
    background-color: #333333; /* Темный фон при наведении */
  }

  .btn-custom.active, .btn-custom:focus {
    color: #ffffff; /* Белый цвет текста для активной кнопки */
    background-color: #A57BCA; /* Светло-фиолетовый фон для активной кнопки */
  }
</style>
<header>
  <nav class="navbar navbar-light" style="background-color: #C062D3">
    <div class="container">
      <a class="navbar-brand" href="{% url 'Pages:index' %}">
        <img src="{% static 'img/logo.png' %}" width="30" height="30" class="d-inline-block align-top" alt="">
        Creating Success
      </a>
      {% with request.resolver_match.view_name as view_name %}
        <ul class="nav nav-pills">
          <li class="nav-item">
            <a class="nav-link custom-link {% if view_name == 'Pages:about' %} active {% endif %}" href="{% url 'Pages:about' %}">
              О проекте
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link custom-link {% if view_name == 'Pages:rules' %} active {% endif %}" href="{% url 'Pages:rules' %}">
              Правила
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link custom-link {% if view_name == 'Blog:category_list' %} active {% endif %}" href="{% url 'Blog:category_list' %}">
              Категории
            </a>
          </li>
          {% if user.is_authenticated %}
          <li class="nav-item">
            <a class="nav-link custom-link {% if view_name == 'Profile:view_profile' %} active {% endif %}" href="{% url 'Profile:view_profile' user.username%}">
              Профиль
            </a>
          </li>
          {% endif %}
          <div class="btn-group" role="group" aria-label="Basic outlined example">
            {% if user.is_authenticated %}
              <form action="{% url 'logout' %}" target="_self">
                <button class="btn btn-outline-dark btn-custom" type="submit">Выйти</button>
              </form>
            {% else %}
              <form action="{% url 'login' %}" target="_self">
                <button class="btn btn-outline-dark btn-custom" type="submit">Войти</button>
              </form>
              <form action="{% url 'registration' %}" target="_self">
                <button class="btn btn-outline-dark btn-custom" type="submit">Регистрация</button>
              </form>
            {% endif %}
          </div>
        </ul>
      {% endwith %}
    </div>
  </nav>
</header>

templates/includes/paginator.html
{% if page_obj.has_other_pages %}
  <nav aria-label="Page navigation" class="my-5">
    <ul class="pagination justify-content-center">
      {% if page_obj.has_previous %}
        <li class="page-item"><a class="page-link" href="?page=1">Первая</a></li>
        <li class="page-item">
          <a class="page-link" href="?page={{ page_obj.previous_page_number }}">
            << </a>
        </li>
      {% endif %}
      {% for i in page_obj.paginator.page_range %}
        {% if page_obj.number == i %}
          <li class="page-item active">
            <span class="page-link">{{ i }}</span>
          </li>
        {% else %}
          <li class="page-item">
            <a class="page-link" href="?page={{ i }}">{{ i }}</a>
          </li>
        {% endif %}
      {% endfor %}
      {% if page_obj.has_next %}
        <li class="page-item">
          <a class="page-link" href="?page={{ page_obj.next_page_number }}">
            >>
          </a>
        </li>
        <li class="page-item">
          <a class="page-link" href="?page={{ page_obj.paginator.num_pages }}">
            Последняя
          </a>
        </li>
      {% endif %}
    </ul>
  </nav>
{% endif %}

templates/includes/post_card.html
<div class="col d-flex justify-content-center">
  <div class="card" style="width: 40rem;">
    <div class="card-body">
      {% if post.image %}
        <a href="{{ post.image.url }}" target="_blank">
          <img class="border-3 rounded img-fluid img-thumbnail mb-2 mx-auto d-block" src="{{ post.image.url }}">
        </a>
      {% endif %}
      <h5 class="card-title">{{ post.title }}</h5>
      <h6 class="card-subtitle mb-2 text-muted">
        <small>
          {% if not post.is_published %}
            <p class="text-danger">Пост снят с публикации админом</p>
          {% elif not post.category.is_published %}
            <p class="text-danger">Выбранная категория снята с публикации админом</p>
          {% endif %}
          {{ post.pub_date|date:"d E Y, H:i" }}
          От автора <a class="text-muted" href="{% url 'Profile:view_profile' post.author.username %}">@{{ post.author.username }}</a> в
          категории {% include "includes/category_link.html" %}
        </small>
      </h6>
      <p class="card-text">{{ post.text|truncatewords:10 }}</p>
      <a href="{% url 'Blog:post_detail' post.id %}" class="card-link">Читать полный текст</a>
      <a href="{% url 'Blog:post_detail' post.id %}" class="card-link text-muted">Комментарии ({{ post.comment_count }})</a>
    </div>
  </div>
</div>

templates/includes/post_content.html
<article>
    <ul>
      <li class='fs-3'>
        {{ post.location }}       
      </li>
      <li class='fs-3'>
        {{ post.date }}
      </li>
      <li class='fs-3'>
        Категория: <a href="{% url 'Blog:category_posts' post.category %}">{{ post.category }}</a>
      </li>
    </ul>         
    <p class='fs-4'>
      {{ post.text }}
    </p>          
</article> 