Blog/urls.py
from django.urls import path

from . import views

app_name = "Blog"

urlpatterns = [

    path(
        "posts/<int:post_id>/",
        views.PostDetailView.as_view(),
        name="post_detail"),

    path(
        'posts/<int:post_id>/edit/',
        views.PostUpdateView.as_view(),
        name='edit_post'),

    path(
        'posts/<int:post_id>/delete/',
        views.PostDeleteView.as_view(),
        name='delete_post'),

    path('posts/create/',
         views.PostCreateView.as_view(),
         name="create_post"),

    path(
        'category/<slug:category_slug>/',
        views.CategoryListView.as_view(),
        name='category_posts',
    ),

    path(
        'categories/',
        views.CategoryAllListView.as_view(),
        name='category_list'),

    path(
        'posts/<int:post_id>/comment/',
        views.CommentCreateView.as_view(),
        name='add_comment',
    ),
    path(
        'posts/<int:post_id>/edit_comment/<int:comment_id>/',
        views.CommentUpdateView.as_view(),
        name='edit_comment',
    ),
    path(
        'posts/<int:post_id>/delete_comment/<int:comment_id>/',
        views.CommentDeleteView.as_view(),
        name='delete_comment',
    ),
]

CreatingSuccess/urls.py
from django.contrib import admin
from django.urls import path, include, reverse_lazy

from django.views.generic.edit import CreateView
from django.conf.urls.static import static
from django.conf import settings
from django.urls import re_path
from django.views.static import serve

from django.contrib.auth.views import (
    LoginView,
    LogoutView,
    PasswordChangeView,
    PasswordResetView,
    PasswordResetConfirmView,
)
from CustomUser.forms import CustomUserCreationForm


handler404 = "Pages.views.page_not_found"
handler500 = "Pages.views.internal_server_error"

urlpatterns = [
    path("admin/", admin.site.urls),

    path("", include("Blog.urls")),

    path("", include("Pages.urls")),

    path("", include("CustomUser.urls")),

    path(
        'registration/',
        CreateView.as_view(
            template_name='registration/registration_form.html',
            form_class=CustomUserCreationForm,

            success_url=reverse_lazy('Pages:index'),
        ),
        name='registration',
    ),

    path(
        'login/',
        LoginView.as_view(template_name='registration/login.html'),
        name='login'
    ),
    path(
        'logout/',
        LogoutView.as_view(),
        name='logout'
    ),
    path(
        'password_change/',
        PasswordChangeView.as_view(template_name='password_change.html'),
        name='password_change'
    ),
    path(
        'password_reset/',
        PasswordResetView.as_view(template_name='password_reset.html'),
        name='password_reset'
    ),
    path(
        'password_reset_confirm/<uidb64>/<token>/',
        PasswordResetConfirmView.as_view(template_name='password_reset_confirm.html'),
        name='password_reset_confirm'
    ),


] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

if not settings.DEBUG:
    urlpatterns += [re_path(r'^media/(?P<path>.*)$',
                            serve,
                            {'document_root': settings.MEDIA_ROOT}),
                    re_path(r'^static/(?P<path>.*)$',
                            serve,
                            {'document_root': settings.STATIC_ROOT}),]

CustomUser/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static

from .views import UserProfileEditView, UserProfileView

app_name = 'Profile'

urlpatterns = [
    path(
        'view/<str:username>/',
        UserProfileView.as_view(),
        name='view_profile'
    ),
    path(
        'edit/<str:username>/',
        UserProfileEditView.as_view(),
        name='edit_profile'
    ),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Blog/models.py
from django.db import models
from django.contrib.auth import get_user_model
from django.urls import reverse

User = get_user_model()


class BaseModel(models.Model):

    is_published = models.BooleanField(
        "Опубликовано",
        default=True,
        help_text="Снимите галочку, чтобы скрыть публикацию.")

    created_at = models.DateTimeField(
        "Добавлено",
        auto_now=False,
        auto_now_add=True)

    class Meta:
        abstract = True


class Category(BaseModel):
    title = models.CharField(
        "Заголовок",
        max_length=256)

    description = models.TextField("Описание")

    slug = models.SlugField(
        "Идентификатор",
        unique=True,
        help_text=("Идентификатор страницы для URL; разрешены символы "
                   "латиницы, цифры, дефис и подчёркивание."))

    class Meta:
        verbose_name = 'категория'
        verbose_name_plural = 'Категории'

    def __str__(self):
        return self.title


class Post(BaseModel):

    title = models.CharField(
        "Заголовок",
        max_length=256)

    text = models.TextField("Текст")

    pub_date = models.DateTimeField(
        "Дата и время публикации",
        help_text=("Если установить дату и время в будущем "
                   "— можно делать отложенные публикации."))

    author = models.ForeignKey(
        User,
        verbose_name="Автор публикации",
        on_delete=models.CASCADE,
        related_name='posts')

    image = models.ImageField(
        verbose_name='Фото',
        upload_to='post_images/',
        blank=True,)

    category = models.ForeignKey(
        Category,
        verbose_name="Категория",
        null=True,
        on_delete=models.SET_NULL,
        related_name='posts')

    class Meta:
        verbose_name = "публикация"
        verbose_name_plural = "Публикации"
        ordering = ("pub_date", "title")

    def get_absolute_url(self) -> str:
        return reverse('Blog:post_detail', kwargs={'pk': self.pk})

    def __str__(self):
        return self.title


class Comment(BaseModel):
    text = models.TextField(
        verbose_name="Текст комментария",)

    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,)

    post = models.ForeignKey(
        Post,
        on_delete=models.CASCADE,
        related_name="comments",)

    class Meta:
        verbose_name = "комментарий"
        verbose_name_plural = "Комментарии"
        ordering = ("created_at",)

    def __str__(self) -> str:
        return f"{self.author}: {self.text[:20]}"

Blog/forms.py
from django import forms
from django.utils import timezone

from .models import Post, Comment


class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        exclude = (
            'author',
            'is_published',)

        widgets = {
            'pub_date': forms.DateTimeInput(
                format='%Y-%m-%dT%H:%M',
                attrs={'type': 'datetime-local'}
            ),
        }

    def clean_pub_date(self):
        pub_date = self.cleaned_data.get('pub_date')
        if pub_date:
            if timezone.is_naive(pub_date):
                pub_date = timezone.make_aware(pub_date)
            pub_date = timezone.localtime(pub_date, timezone.utc)
        return pub_date


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('text',)
        widgets = {
            'text': forms.Textarea(
                attrs={'rows': '5'}
            )
        }

Blog/views.py
from django.shortcuts import get_object_or_404, redirect, render
from django.utils import timezone
from django.db.models import Count, Q
from django.http import Http404
from django.contrib.auth import get_user_model
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic import (
    ListView, CreateView, UpdateView, DeleteView, DetailView)
from django.urls import reverse

from .forms import PostForm, CommentForm
from .models import Post, Category, Comment

POSTS_PER_PAGE = 10
CATEGORIES_PER_PAGE = 5


def annotate_total_amount(queryset):
    return queryset.annotate(comment_count=Count('comments'))


def select_related_fields(queryset):
    return queryset.select_related('author', 'category')


def order_by_field(queryset, field):
    return queryset.order_by(field)


def post_filter(self, target=None):
    queryset = annotate_total_amount(Post.objects)
    queryset = select_related_fields(queryset)
    queryset = order_by_field(queryset, '-pub_date')
    if target == 'profile':
        queryset = queryset.filter(author=self.author)
    else:
        queryset = queryset.filter(
            is_published=True,
            pub_date__lte=timezone.now(),
            category__is_published=True,)
    print(timezone.localtime(timezone.now()))
    return queryset


User = get_user_model()


class RedirectionPostMixin:
    def get_success_url(self):
        return reverse(
            'Blog:post_detail',
            kwargs={'post_id': self.kwargs['post_id']}
        )


class RedirectionProfileMixin:
    def get_success_url(self):
        return reverse(
            'Profile:view_profile',
            kwargs={'username': self.request.user}
        )


class PostMixin:
    model = Post


class PostFormMixin(PostMixin):
    form_class = PostForm


class SetAutorMixin:
    def form_valid(self, form):
        form.instance.author = self.request.user
        return super().form_valid(form)


class PostListMixin(ListView):
    paginate_by = POSTS_PER_PAGE


class PostCreateView(
    LoginRequiredMixin,
    PostFormMixin,
    SetAutorMixin,
    RedirectionProfileMixin,
    CreateView,
):
    template_name = 'blog/create.html'


class PostDetailView(PostMixin, DetailView):
    template_name = 'blog/detail.html'
    pk_url_kwarg = 'post_id'

    def get_queryset(self):
        return select_related_fields(super().get_queryset())

    def get_object(self, queryset=None):

        post = super().get_object(queryset)
        if post.author != self.request.user and (
            post.is_published is False
            or post.category.is_published is False
            or post.pub_date > timezone.now()
        ):
            raise Http404
        return post

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['form'] = CommentForm()
        context['comments'] = self.object.comments.select_related(
            'author'
        )
        return context


class CommentMixin(RedirectionPostMixin):
    model = Comment
    template_name = 'blog/comment.html'
    pk_url_kwarg = 'comment_id'


class CommentFormMixin(CommentMixin):
    form_class = CommentForm


class EditContentMixin(LoginRequiredMixin):

    def dispatch(self, request, *args, **kwargs):
        if self.get_object().author != request.user:
            return redirect(
                'Blog:post_detail',
                post_id=self.kwargs['post_id']
            )
        return super().dispatch(request, *args, **kwargs)


class CommentCreateView(LoginRequiredMixin, CommentFormMixin, CreateView):

    def form_valid(self, form):
        form.instance.author = self.request.user
        form.instance.post = get_object_or_404(
            post_filter(self),
            pk=self.kwargs['post_id']
        )
        return super().form_valid(form)


class CommentUpdateView(EditContentMixin, CommentFormMixin, UpdateView):
    pass


class CommentDeleteView(EditContentMixin, CommentMixin, DeleteView):
    pass


class PostIdCreateMixin:
    template_name = 'blog/create.html'
    pk_url_kwarg = 'post_id'


class PostUpdateView(
    EditContentMixin,
    PostFormMixin,
    PostIdCreateMixin,
    SetAutorMixin,
    RedirectionPostMixin,
    UpdateView,
):
    pass


class PostDeleteView(
    EditContentMixin,
    PostMixin,
    PostIdCreateMixin,
    RedirectionProfileMixin,
    DeleteView,
):

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['form'] = PostForm(instance=self.object)
        return context


class CategoryListView(PostListMixin):

    template_name = 'blog/category.html'

    def get_queryset(self):
        return post_filter(self).filter(
            category__slug=self.kwargs['category_slug'],
        )

    def get_context_data(self, **kwargs):

        context = super().get_context_data(**kwargs)
        context['category'] = get_object_or_404(
            Category,
            is_published=True,
            slug=self.kwargs['category_slug'],
        )
        return context


class CategoryAllListView(PostListMixin):
    model = Category
    template_name = 'category_list.html'
    context_object_name = 'categories'
    paginate_by = CATEGORIES_PER_PAGE

    def get_queryset(self):

        search_query = self.request.GET.get('search', '')

        if search_query:
            return Category.objects.filter(
                Q(title__icontains=search_query) |
                Q(description__icontains=search_query)
            )
        else:
            return Category.objects.all()

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        context['search_query'] = self.request.GET.get('search', '')
        return context

templates/blog/category.html
{% extends "base.html" %}
{% block title %}
  Публикации в категории {{ category.title }}
{% endblock %}
{% block content %}
  <h1 class="text-center">Публикации в категории - {{ category.title }}</h1>
  <p class="col-6 offset-3 mb-5 lead text-center">{{ category.description }}</p>
  {% for post in page_obj %}
    <article class="mb-5">  
      {% include "includes/post_card.html" %}
    </article>   
  {% endfor %}
  {% include "includes/paginator.html" %}
{% endblock %}

templates/blog/category_list.html
{% extends "base.html" %}
{% block title %}
  Все категории
{% endblock %}

{% block content %}
<style>
    .category-list {
        list-style-type: none; 
        padding: 0;
    }
    
    .category-item {
        background-color: #fff;
        border: 1px solid #ddd;
        border-radius: 5px;
        padding: 15px;
        margin-bottom: 15px;
        transition: box-shadow 0.3s;
    }
    
    .category-item:hover {
        box-shadow: 0 4px 10px rgba(0, 0, 0, 0.2);
    }
    
    .category-link {
        text-decoration: none;
        color: #007bff;
    }
    
    .category-link:hover {
        text-decoration: underline;
    }

    .search-form {
        margin-bottom: 20px;
    }

    .paginator {
        margin-top: 20px;
    }
</style>

<form method="get" action="" class="search-form">
    <input type="text" name="search" value="{{ search_query }}" placeholder="Поиск по категории..." />
    <button type="submit">Поиск</button>
</form>


<ul class="category-list">
    {% for category in categories %}
    <li class="category-item">
        <h2>{{ category.title }}</h2>
        <p>{{ category.description }}</p>
        <a class="category-link" href="{% url 'Blog:category_posts' category.slug %}">Узнать больше</a>
    </li>
    {% empty %}
    <li class="category-item">Нет доступных категорий.</li>
    {% endfor %}
</ul>
{% include "includes/paginator.html" %}
{% endblock %}

templates/blog/comment.html
{% extends "base.html" %}
{% load django_bootstrap5 %}
{% block title %}
  {% if '/edit_comment/' in request.path %}
    Редактирование комментария
  {% else %}
    Удаление комментария
  {% endif %}
{% endblock %}
{% block content %}
  {% if user.is_authenticated %}
    <div class="col d-flex justify-content-center">
      <div class="card" style="width: 40rem;">
        <div class="card-header">
          {% if '/edit_comment/' in request.path %}
            Редактирование комментария
          {% else %}
            Удаление комментария
          {% endif %}
        </div>
        <div class="card-body">
          <form method="post"
            {% if '/edit_comment/' in request.path %}
              action="{% url 'Blog:edit_comment' comment.post_id comment.id %}"
            {% endif %}>
            {% csrf_token %}
            {% if not '/delete_comment/' in request.path %}
              {% bootstrap_form form %}
            {% else %}
              <p>{{ comment.text }}</p>
            {% endif %}
            {% bootstrap_button button_type="submit" content="Отправить" %}
          </form>
        </div>
      </div>
    </div>
  {% endif %}
{% endblock %}

templates/blog/create.html
{% extends "base.html" %}
{% load django_bootstrap5 %}
{% block title %}
  {% if '/edit/' in request.path %}
    Редактирование публикации
  {% elif "/delete/" in request.path %}
    Удаление публикации
  {% else %}
    Добавление публикации
  {% endif %}
{% endblock %}
{% block content %}
  <div class="col d-flex justify-content-center">
    <div class="card" style="width: 40rem;">
      <div class="card-header">
        {% if '/edit/' in request.path %}
          Редактирование публикации
        {% elif '/delete/' in request.path %}
          Удаление публикации
        {% else %}
          Добавление публикации
        {% endif %}
      </div>
      <div class="card-body">
        <form method="post" enctype="multipart/form-data">
          {% csrf_token %}
          {% if not '/delete/' in request.path %}
            {% bootstrap_form form %}
          {% else %}
            <article>
              {% if form.instance.image %}
                <a href="{{ form.instance.image.url }}" target="_blank">
                  <img class="border-3 rounded img-fluid img-thumbnail mb-2" src="{{ form.instance.image.url }}">
                </a>
              {% endif %}
              <p>{{ form.instance.pub_date|date:"d E Y" }} </p>
              <h3>{{ form.instance.title }}</h3>
              <p>{{ form.instance.text|linebreaksbr }}</p>
            </article>
          {% endif %}
          {% bootstrap_button button_type="submit" content="Отправить" %}
        </form>
      </div>
    </div>
  </div>
{% endblock %}

templates/blog/detail.html
{% extends "base.html" %}
{% block title %}
  {{ post.title }}
  {{ post.pub_date|date:"d E Y" }}
{% endblock %}
{% block content %}
  <div class="col d-flex justify-content-center">
    <div class="card" style="width: 40rem;">
      <div class="card-body">
        {% if post.image %}
          <a href="{{ post.image.url }}" target="_blank">
            <img class="border-3 rounded img-fluid img-thumbnail mb-2 mx-auto d-block" src="{{ post.image.url }}">
          </a>
        {% endif %}
        <h5 class="card-title">{{ post.title }}</h5>
        <h6 class="card-subtitle mb-2 text-muted">
          <small>
            {% if not post.is_published %}
              <p class="text-danger">Пост снят с публикации админом</p>
            {% elif not post.category.is_published %}
              <p class="text-danger">Выбранная категория снята с публикации админом</p>
            {% endif %}
            {{ post.pub_date|date:"d E Y, H:i" }}
            От автора <a class="text-muted" href="{% url 'Profile:view_profile' post.author.username %}">@{{ post.author.username }}</a> в
            категории {% include "includes/category_link.html" %}
          </small>
        </h6>
        <p class="card-text">{{ post.text|linebreaksbr }}</p>
        {% if user == post.author %}
          <div class="mb-2">
            <a class="btn btn-sm text-muted" href="{% url 'Blog:edit_post' post.id %}" role="button">
              Отредактировать публикацию
            </a>
            <a class="btn btn-sm text-muted" href="{% url 'Blog:delete_post' post.id %}" role="button">
              Удалить публикацию
            </a>
          </div>
        {% endif %}
        {% include "includes/comments.html" %}
      </div>
    </div>
  </div>
{% endblock %}

templates/blog/index.html
{% extends "base.html" %}
{% block title %}
  Лента записей
{% endblock %}
{% block content %}
  {% for post in page_obj %}
    <article class="mb-5">
      {% include "includes/post_card.html" %}
    </article>
  {% endfor %}
  {% include "includes/paginator.html" %}
{% endblock %}

templates/blog/profile.html
{% extends "base.html" %}
{% block title %}
  Страница пользователя {{ profile.username }}
{% endblock %}
{% block content %}
  <h1 class="mb-5 text-center ">Страница пользователя {{ profile.username }}</h1>
  <small>
    <ul class="list-group list-group-horizontal justify-content-center mb-3">
      <li class="list-group-item text-muted">Имя пользователя: {% if profile.get_full_name %}{{ profile.get_full_name }}{% else %}не указано{% endif %}</li>
      <li class="list-group-item text-muted">Регистрация: {{ profile.date_joined }}</li>
      <li class="list-group-item text-muted">Роль: {% if profile.is_staff %}Админ{% else %}Пользователь{% endif %}</li>
    </ul>
    <ul class="list-group list-group-horizontal justify-content-center">
      {% if user.is_authenticated and request.user == profile %}
      <a class="btn btn-sm text-muted" href="{% url 'blog:edit_profile' %}">Редактировать профиль</a>
      <a class="btn btn-sm text-muted" href="{% url 'password_change' %}">Изменить пароль</a>
      {% endif %}
    </ul>
  </small>
  <br>
  <h3 class="mb-5 text-center">Публикации пользователя</h3>
  {% for post in page_obj %}
    <article class="mb-5">
      {% include "includes/post_card.html" %}
    </article>
  {% endfor %}
  {% include "includes/paginator.html" %}
{% endblock %}

templates/blog/user.html
{% extends "base.html" %}
{% load django_bootstrap5 %}
{% block title %}
  Редактирование профиля
{% endblock %}
{% block content %}
  <div class="col d-flex justify-content-center">
    <div class="card" style="width: 40rem;">
      <div class="card-header">
        Редактирование профиля - {{ request.user.username }}
      </div>
      <div class="card-body">
        <form method="post">
          {% csrf_token %}
          {% bootstrap_form form %}
          {% bootstrap_button button_type="submit" content="Отправить" %}
        </form>
      </div>
    </div>
  </div>
{% endblock %}